locator_searchbox="//input[@id='search_focus_desktop']"
locator_btn_search="//input[@id='search_focus_desktop']/../a[@title='Begin your search']"
# locator_btn_addtocart="//div[@class='purchase-info ']//button[text()='Add to cart']"
locator_btn_addtocart="(//span[@class='cta_price']//a[@id='add2cart-btn'])[1]"

# locator_searchbox_pdp="//input[@aria-label='Search hp.com']"
locator_searchbox_pdp="//input[@id='search_focus_desktop']"
locator_btn_search_pdp="//input[@aria-label='Search hp.com']/../button"
miniCartIcon="//button[@aria-label='Shopping Cart']"
locator_miniCartViewAll="//div[@class='minicart_title']/a[text()='View all items >']"

locator_btn_paypalcheckout="//div[@class='xo_loginbox']//div[@id='paypalDiv']/div"

searched_vlue = "HP 470 G7 Notebook PC"
search_laptop = "//input[@id='search_focus_desktop']"
# click_element = "//body/div[@id='header']/div[2]/div[1]/div[1]/div[2]/div[1]/a[1]"
click_element = "//body/div[@id='header']/div[2]/nav[1]/div[1]/div[1]/div[2]/div[1]/a[1]"
search_result='//*[@id="PLPPageTitle"][contains(text(),"Results")]'
laptop_search = "Results for 'HP 470 G7 Notebook PC'"
# Sto_checkout = "(//a[@id='add2cart-btn'])[1]"
Sto_checkout = "(//a[@id='add2cart-btn'])[1]"
Checkout_cart = "//div[@class='minicarttitle']"
checkout_guest = "//div[@class='guestcheckout']/a"
Secure_checkout = "//div[@class='lcHeaderInner']"
shipping_met = "//span[@id='shipoption-desc12056']"
ship_charge = "(//div[@class='lblRcSummaryRt orderShipChg'])[1]"
taxes = "(//div[@class='lblRcSummaryRt orderTaxes'])[1]"
total = "(//div[@class='lblRcSummaryRt orderTotal'])[1]"
mouseon_monicart = "//div[@class='hdr_buttons']"
Click_guest = "//div[@class='minicarttitle']/a"
shipping_meth = "(//span[@class='chktext'])[2]"
bto_product_items = "C9V73A8#ABA"